version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "8081:80"

  javaapp:
    build: .
    container_name: javaapp
    depends_on:
      - mariadb
    environment:
      DB_URL: jdbc:mariadb://mariadb:3306/${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_USER_PASS}
      #JWT_SECRET: ${JWT_SECRET}
      #JWT_EXPIRATION: ${JWT_EXPIRATION}
